### ISSUE TITLE
Does RMS support sensitivity analysis?

### ISSUE THREAD

**Issue by jiweiqi** [ReactionMechanismGenerator/ReactionMechanismSimulator.jl#28]
For now, does rms support sensitivity analysis for zero-D simulations? What kind of sensitivity analysis algorithm it takes for now?

**Comment by mjohnson541** [comment]
So v0.1.0 uses analytic Jacobians and forward sensitivity analysis (dS/dt = J_y * S + J_p). Currently master is supposed to support forward sensitivity analysis using auto-diff, but it has a bug in it and I haven't put much effort into fixing it because I'm about to revamp how it does things and integrate Julia DifferentialEquations better. After the revamp it should be trivial to enable it use any of Julia DifferentialEquations' sensitivity algorithms. Later I'm planning to add sparse auto diff, at least for simpler simulations but one thing at a time XD.

**Comment by ChrisRackauckas** [comment]
Hey, just found this library, nice work. If you integrate with DiffEq's sensitivity algorithms, sparse autodiff will automatically work for sensitivity analysis: https://github.com/SciML/DiffEqSensitivity.jl/pull/284 . All you have to do is provide a sparse matrix for the Jacobian in the `ODEFunction` construction, since all of the color vector handling is now automatic.

**Comment by jiweiqi** [comment]
Hi @ChrisRackauckas Thanks for your suggestion. This package is going to boost Julia and DiffEq in combustion community, which also heavily rely on stiff ODE solver as biochemistry. Regarding the sparse sensitivity, is there any link describe the benefit of sparse matrix here? In the forward sensitivity analysis (dS/dt = J_y * S + J_p), is the sparse referring to J_y or J_p? Or both. 

BTW, I plan to also adopt adjoint sensitivity here, which we have discussed quite a lot in the Julia slack channel.

**Comment by mjohnson541** [comment]
Thanks! 

So the benefit is that pretty much all of the 0-D reaction systems we can pose can be formulated in a sparse way. Currently ConstantTPDomain is not formatted that way...I have a branch somewhere where I was reformulating it, but it's old...but the other ones are sparse in both Jy and Jp. Unfortunately, in the case of Jy except for the liquid phase reactors we get thermodynamic coupling through volume or temperature that creates at least one dense row and column. The dense column isn't a problem, but that dense row prevents a simple application of SparseDiffTools. Fortunately, the dense rows are not too hard to write analytic formulas for. So my plan has been to use SparseDiffTools for the chemical species jacobian which is sparse in the row sense and then calculate the thermodynamic differential variable rows analytically and the columns with regular autodiff. 

I have a branch where I've fixed the types so that it's compatible enough with FowardDiff, ReverseDiff and Tracker that I can run forward and adjoint sensitivity analysis, however, while forward sensitivity analysis works, currently adjoint is blocked for the moment by:  
https://github.com/SciML/DiffEqSensitivity.jl/issues/282 and https://github.com/SciML/DiffEqSensitivity.jl/issues/92

**Comment by ChrisRackauckas** [comment]
>Regarding the sparse sensitivity, is there any link describe the benefit of sparse matrix here? In the forward sensitivity analysis (dS/dt = J_y * S + J_p), is the sparse referring to J_y or J_p? Or both.

Neither of those matrices are formed in full. The Jacobian-vector product is done in a fully sparse form no matter what.

>So the benefit is that pretty much all of the 0-D reaction systems we can pose can be formulated in a sparse way. Currently ConstantTPDomain is not formatted that way...I have a branch somewhere where I was reformulating it, but it's old...but the other ones are sparse in both Jy and Jp. Unfortunately, in the case of Jy except for the liquid phase reactors we get thermodynamic coupling through volume or temperature that creates at least one dense row and column. The dense column isn't a problem, but that dense row prevents a simple application of SparseDiffTools. Fortunately, the dense rows are not too hard to write analytic formulas for. So my plan has been to use SparseDiffTools for the chemical species jacobian which is sparse in the row sense and then calculate the thermodynamic differential variable rows analytically and the columns with regular autodiff.

That just requires feeding the colorvec appropriately to a reverse-mode AD. Open an issue on SparseDiffTools and we can get it implemented. Though if an analytical solution can exist, it will be faster, and something like ModelingToolkit can probably help generate it.

>currently adjoint is blocked for the moment by:
SciML/DiffEqSensitivity.jl#282 and SciML/DiffEqSensitivity.jl#92

Oh yes, pinging @yingboma on that one again. We should just get it fixed ASAP

**Comment by mjohnson541** [comment]
Oh...didn't think about that...that's a really nice solution! 

The plan is to definitely to have analytic for cases when the rate coefficients are constant, for most single domain cases with variable rate coefficients analytic except for the themodynamic (T,V) columns should work pretty well, but once I enable coupling between reaction domains (gas and liquid, gas and catalyst, pipe to another reactor) or add other mass transfer processes  analytic solutions will quickly become impractical.

**Comment by mjohnson541** [comment]
As of #46 RMS supports forward and adjoint sensitivity analysis resolving the primary part of this issue. The discussion of automatic sparse differentiation is continued in #57.
